### ISSUE TITLE
服务端运行./dnsd server 0.0.0.0:1234 1.1.1.1:53 log_off 报错

### ISSUE THREAD

**Issue by kankankankankankan** [develon2015/dnsd#1]
无法启用监听服务: invalid socket address
Error: Custom { kind: InvalidInput, error: "invalid socket address" }

版本21.07.22

感谢！

**Comment by develon2015** [comment]
C/S架构已编译上传，https://github.com/develon2015/dnsd/releases/tag/21.10.14

**Comment by kankankankankankan** [comment]
感谢已解决
